name: election
dependencies:
    - python=3.5
    - numpy
    - pandas
    - jupyter
    - notebook
    - seaborn
    - watermark
    - theano
    - setuptools>=27.2.0
    - us
    - pip:
        - pollster
        - git+https://github.com/pymc-devs/pymc3.git#egg=pymc3